### ISSUE TITLE
ModuleNotFoundError for scripts in scripts directory

### ISSUE THREAD

**Issue by jacobay43** [getnamo/ml-remote-server#4]
Really awesome work you've done with this project. I am having an issue with the setup following the instructions of linking this to the MachineLearningRemote component in UE4. It keeps not finding the DefaultScript saying scripts/<script-name> not found. Here is the full traceback.

In [6]: !python server.py
MLPluginAPI imported
link set
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
connect  kAmg2jtkoneDAVTEAAAB
loading <hello.py>
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py:506> exception=ModuleNotFoundError("No module named 'scripts.hello'")>
Traceback (most recent call last):
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py", line 508, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py", line 542, in _trigger_event
    ret = await handler(*args)
  File "server.py", line 103, in start_script
    valid, err = mlp.load(script_name)
  File "C:\Users\LENOVO\Downloads\ml-remote-server-master\mlplugin.py", line 33, in load
    active_script = importlib.import_module(script_folder + '.' + script_name)
  File "C:\Users\LENOVO\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.hello'
sendInput: {'inputData': 'UE4 ML remote', 'targetFunction': 'onJsonInput'}
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py:506> exception=RuntimeError('Task <Task pending coro=<AsyncServer._handle_event_internal() running at C:\\Users\\LENOVO\\Anaconda3\\lib\\site-packages\\socketio\\asyncio_server.py:508>> got Future <Future pending> attached to a different loop')>
Traceback (most recent call last):
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py", line 508, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py", line 542, in _trigger_event
    ret = await handler(*args)
  File "server.py", line 97, in send_input
    return await future
RuntimeError: Task <Task pending coro=<AsyncServer._handle_event_internal() running at C:\Users\LENOVO\Anaconda3\lib\site-packages\socketio\asyncio_server.py:508>> got Future <Future pending> attached to a different loop
disconnect kAmg2jtkoneDAVTEAAAB

**Comment by jacobay43** [comment]
Okay. After some time, I was able to solve this by adding an empty __init__.py in the scripts directory
